# Generated by Django 3.1 on 2021-03-10 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='job_titles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='workers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('login_email', models.EmailField(max_length=50)),
                ('login_password', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_log.genders')),
                ('job_title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_log.job_titles')),
            ],
        ),
    ]
