# Generated by Django 3.1.7 on 2021-03-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_log', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='benificiaries',
            new_name='beneficiaries',
        ),
        migrations.RenameModel(
            old_name='benificiary_statuses',
            new_name='beneficiary_statuses',
        ),
        migrations.RenameField(
            model_name='beneficiaries',
            old_name='benificiary_status_id',
            new_name='beneficiary_status_id',
        ),
        migrations.RenameField(
            model_name='beneficiary_statuses',
            old_name='benificiary_status',
            new_name='beneficiary_status',
        ),
    ]
