# Generated by Django 3.1.7 on 2021-03-20 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_log', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nationalities',
        ),
        migrations.DeleteModel(
            name='nationalitiess',
        ),
    ]
