# Generated by Django 3.1.7 on 2021-03-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_log', '0002_auto_20210320_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='nationalities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nationality', models.CharField(max_length=50)),
            ],
        ),
    ]
