# Generated by Django 3.1.7 on 2021-03-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_log', '0003_nationalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='nationality_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='case_log.nationalities'),
            preserve_default=False,
        ),
    ]
