# Generated by Django 3.1.7 on 2021-04-01 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FileNum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PsWorker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caselog.gender')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caselog.nationality')),
            ],
        ),
        migrations.CreateModel(
            name='MonthLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caselog.case')),
                ('casestatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caselog.casestatus')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caselog.month')),
            ],
        ),
        migrations.CreateModel(
            name='IndirectBenef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caselog.gender')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caselog.nationality')),
            ],
        ),
        migrations.CreateModel(
            name='DirectBenef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caselog.gender')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caselog.nationality')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='casetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caselog.casetype'),
        ),
        migrations.AddField(
            model_name='case',
            name='directbenef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caselog.directbenef'),
        ),
        migrations.AddField(
            model_name='case',
            name='filenum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caselog.filenum'),
        ),
        migrations.AddField(
            model_name='case',
            name='indirectbenefs',
            field=models.ManyToManyField(to='caselog.IndirectBenef'),
        ),
        migrations.AddField(
            model_name='case',
            name='psworkers',
            field=models.ManyToManyField(to='caselog.PsWorker'),
        ),
    ]
