# Generated by Django 3.1.7 on 2021-04-02 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caselog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='directbenef',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='caselog.directbenef'),
        ),
    ]
