# Generated by Django 3.1.7 on 2021-04-20 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caselog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April')], max_length=200, null=True)),
                ('filenumber', models.CharField(max_length=50)),
                ('casestatus', models.CharField(choices=[('New', 'New'), ('Ongoing', 'Ongoing'), ('Inactive', 'Inactive'), ('Closed', 'Closed')], max_length=200, null=True)),
                ('casetype', models.CharField(choices=[('Individual', 'Individual'), ('Family', 'Family')], max_length=200, null=True)),
                ('fullname', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True)),
                ('nationality', models.CharField(choices=[('Syria', 'Syria'), ('Sudan', 'Sudan'), ('S. Sudan', 'S. Sudan'), ('Ethiopia', 'Ethiopia'), ('Iraq', 'Iraq'), ('Somalia', 'Somalia'), ('Eritrea', 'Eritrea'), ('Yemen', 'Yemen'), ('Comoros', 'Comoros'), ('Cameron', 'Cameron')], max_length=200, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(choices=[('Alexandria', 'Alexandria'), ('Damietta', 'Damietta'), ('Mansoura', 'Mansoura'), ('6th of October', '6th of October'), ('Ain Shams', 'Ain Shams'), ('10th of Ramadan', '10th of Ramadan')], max_length=50, null=True)),
                ('referralsource', models.CharField(choices=[('UNHCR', 'UNHCR'), ('Community', 'Community'), ('SCI', 'SCI'), ('StARS', 'StARS'), ('Tdh', 'Tdh'), ('PSTIC Hot Line', 'PSTIC Hot Line'), ('Egypt Refuge', 'Egypt Refuge'), ('IOM', 'IOM')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitdate', models.CharField(max_length=200, null=True)),
                ('comment', models.CharField(max_length=1000, null=True)),
                ('logentry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caselog.logentry')),
            ],
        ),
        migrations.RemoveField(
            model_name='directbenef',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='directbenef',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='monthlog',
            name='case',
        ),
        migrations.RemoveField(
            model_name='monthlog',
            name='casestatus',
        ),
        migrations.RemoveField(
            model_name='monthlog',
            name='month',
        ),
        migrations.RemoveField(
            model_name='case',
            name='casetype',
        ),
        migrations.RemoveField(
            model_name='case',
            name='directbenef',
        ),
        migrations.RemoveField(
            model_name='case',
            name='indirectbenefs',
        ),
        migrations.AddField(
            model_name='psworker',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='psworker',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='psworker',
            name='profilepic',
            field=models.ImageField(blank=True, default='profile_pic.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='psworker',
            name='team',
            field=models.CharField(choices=[('NC', 'NC'), ('Cairo', 'Cairo')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='psworker',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='filenum',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='psworkers',
            field=models.ManyToManyField(null=True, to='caselog.PsWorker'),
        ),
        migrations.AlterField(
            model_name='indirectbenef',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='indirectbenef',
            name='nationality',
            field=models.CharField(choices=[('Syria', 'Syria'), ('Sudan', 'Sudan'), ('S. Sudan', 'S. Sudan'), ('Ethiopia', 'Ethiopia'), ('Iraq', 'Iraq'), ('Somalia', 'Somalia'), ('Eritrea', 'Eritrea'), ('Yemen', 'Yemen'), ('Comoros', 'Comoros'), ('Cameron', 'Cameron')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='psworker',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='psworker',
            name='nationality',
            field=models.CharField(choices=[('Syria', 'Syria'), ('Sudan', 'Sudan'), ('S. Sudan', 'S. Sudan'), ('Ethiopia', 'Ethiopia'), ('Iraq', 'Iraq'), ('Somalia', 'Somalia'), ('Eritrea', 'Eritrea'), ('Yemen', 'Yemen'), ('Comoros', 'Comoros'), ('Cameron', 'Cameron')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='CaseStatus',
        ),
        migrations.DeleteModel(
            name='CaseType',
        ),
        migrations.DeleteModel(
            name='DirectBenef',
        ),
        migrations.DeleteModel(
            name='FileNum',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='MonthLog',
        ),
        migrations.DeleteModel(
            name='Nationality',
        ),
        migrations.AddField(
            model_name='logentry',
            name='psworker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caselog.psworker'),
        ),
        migrations.AddField(
            model_name='indirectbenef',
            name='logentry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caselog.logentry'),
        ),
    ]
