# Generated by Django 3.1.7 on 2021-04-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caselog', '0002_auto_20210402_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='filenum',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='psworkers',
            field=models.ManyToManyField(related_name='Cases', to='caselog.PsWorker'),
        ),
        migrations.DeleteModel(
            name='FileNum',
        ),
    ]
