# Generated by Django 3.1.7 on 2021-04-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caselog', '0003_auto_20210402_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='casetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caselog.casetype'),
        ),
        migrations.AlterField(
            model_name='case',
            name='directbenef',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='caselog.directbenef'),
        ),
        migrations.AlterField(
            model_name='case',
            name='indirectbenefs',
            field=models.ManyToManyField(null=True, to='caselog.IndirectBenef'),
        ),
        migrations.AlterField(
            model_name='case',
            name='psworkers',
            field=models.ManyToManyField(null=True, related_name='Cases', to='caselog.PsWorker'),
        ),
    ]
