# Generated by Django 3.1.7 on 2021-04-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caselog', '0004_auto_20210402_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directbenef',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
