# Generated by Django 3.1.7 on 2021-04-02 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caselog', '0005_auto_20210402_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directbenef',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caselog.gender'),
        ),
        migrations.AlterField(
            model_name='directbenef',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caselog.nationality'),
        ),
    ]
