# Generated by Django 3.1.7 on 2021-04-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caselog', '0006_auto_20210402_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='indirectbenefs',
        ),
        migrations.AddField(
            model_name='case',
            name='indirectbenefs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caselog.indirectbenef'),
        ),
        migrations.AlterField(
            model_name='case',
            name='psworkers',
            field=models.ManyToManyField(null=True, to='caselog.PsWorker'),
        ),
    ]
