# Generated by Django 3.1.7 on 2021-04-03 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caselog', '0007_auto_20210403_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='indirectbenefs',
        ),
        migrations.AddField(
            model_name='indirectbenef',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caselog.case'),
        ),
    ]
