# Generated by Django 3.1.7 on 2021-04-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caselog', '0008_auto_20210403_1247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthLog',
            new_name='LogEntry',
        ),
    ]
