# Generated by Django 3.1.7 on 2021-04-03 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caselog', '0009_auto_20210403_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='casetype',
        ),
        migrations.RemoveField(
            model_name='case',
            name='directbenef',
        ),
        migrations.AddField(
            model_name='logentry',
            name='casetype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='caselog.casetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='dage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='dfullname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logentry',
            name='dgender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caselog.gender'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='dnationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caselog.nationality'),
        ),
        migrations.DeleteModel(
            name='DirectBenef',
        ),
    ]
