# Generated by Django 3.1.7 on 2021-04-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caselog', '0011_auto_20210408_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='referralsource',
            field=models.CharField(choices=[('UNHCR', 'UNHCR'), ('Community', 'Community'), ('SCI', 'SCI'), ('StARS', 'StARS'), ('Tdh', 'Tdh'), ('PSTIC Hot Line', 'PSTIC Hot Line'), ('Egypt Refuge', 'Egypt Refuge'), ('IOM', 'IOM')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April')], max_length=200, null=True),
        ),
    ]
