# Generated by Django 3.1.7 on 2021-04-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caselog', '0012_auto_20210409_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='location',
            field=models.CharField(choices=[('Alexandria', 'Alexandria'), ('Damietta', 'Damietta'), ('Mansoura', 'Mansoura'), ('6th of October', '6th of October'), ('Ain Shams', 'Ain Shams'), ('10th of Ramadan', '10th of Ramadan')], max_length=50, null=True),
        ),
    ]
