# Generated by Django 3.1.7 on 2021-04-09 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caselog', '0013_auto_20210409_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='psworker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caselog.psworker'),
        ),
        migrations.AddField(
            model_name='psworker',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='psworker',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
