# Generated by Django 3.1.7 on 2021-04-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caselog', '0017_psworker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='psworker',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
