# Generated by Django 3.1.7 on 2021-04-12 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caselog', '0018_psworker_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='indirectbenefs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caselog.indirectbenef'),
        ),
        migrations.AlterField(
            model_name='psworker',
            name='profilepic',
            field=models.ImageField(blank=True, default='profile_pic.png', null=True, upload_to=''),
        ),
    ]
