# Generated by Django 3.1.7 on 2021-04-12 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caselog', '0019_auto_20210412_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitdate', models.CharField(max_length=200, null=True)),
                ('comment', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='indirectbenef',
            name='case',
        ),
        migrations.AddField(
            model_name='logentry',
            name='visits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caselog.visit'),
        ),
    ]
