# Generated by Django 3.1.7 on 2021-04-13 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caselog', '0020_auto_20210412_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='indirectbenefs',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='visits',
        ),
        migrations.AddField(
            model_name='indirectbenef',
            name='logentry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caselog.logentry'),
        ),
        migrations.AddField(
            model_name='visit',
            name='logentry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caselog.logentry'),
        ),
    ]
