# Generated by Django 3.1.7 on 2021-04-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caselog', '0022_auto_20210413_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visitdate',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
